require("pixprocoder.plugins-setup")
require("pixprocoder.core.options")
require("pixprocoder.core.keymaps")
require("pixprocoder.core.colorscheme")
require("pixprocoder.plugins.comment")
require("pixprocoder.plugins.nvim-tree")
require("pixprocoder.plugins.lualine")
require("pixprocoder.plugins.telescope")
require("pixprocoder.plugins.lsp.mason")
require("pixprocoder.plugins.lsp.null-ls")
require("pixprocoder.plugins.autopairs")
require("pixprocoder.plugins.treesitter")
require("pixprocoder.plugins.gitsigns")

-- require("pixprocoder.plugins.lsp.lspsoga")
-- require("pixprocoder.plugins.lsp.lspconfig")
-- Configure the Lua language server using lspconfig
