require("pixprocoder.plugins-setup")
require("pixprocoder.core.options")
require("pixprocoder.core.keymaps")
require("pixprocoder.core.colorscheme")
require("pixprocoder.plugins.comment")
require("pixprocoder.plugins.nvim-tree")
require("pixprocoder.plugins.lualine")
require("pixprocoder.plugins.telescope")
require("pixprocoder.plugins.lsp.lspconfig")
require("pixprocoder.plugins.lsp.mason")
-- Configure the Lua language server using lspconfig
